name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      env:
        POETRY_VERSION: "1.7.1"
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
        else
          curl -sSL https://install.python-poetry.org | python3 -
        fi
      shell: bash

    - name: Add Poetry to Path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH
        else
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi
      shell: bash

    - name: Configure Poetry virtual environment in project
      run: poetry config virtualenvs.in-project true
      shell: bash

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: poetry install -E pydantic --no-interaction
      shell: bash
